[package]
name = "video_stream"
version = "0.1.0"
edition = "2021"
authors = ["Diogo Cidral"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.96"

[profile.release]
debug = "line-tables-only"