[package]
name = "omni_pane"
version = "0.1.0"
edition = "2021"
authors = ["Diogo Cidral"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.98.1"
chrono = "0.4.42"

[profile.release]
debug = "line-tables-only"